Classroom/Models/DB_Models/StudentTasks.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Classroom.Models.DB_Models
{
    public class StudentTasks
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public int TaskId { get; set; }
        [AllowHtml]
        public double Mark { get; set; }
    }
}

Classroom/Models/DB_Models/Subject.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Classroom.Models.DB_Models
{
    public partial class Subject
    {
        public int Id { get; set; }
        public string Name { get; set; }
        //public virtual Student Student { get; set; }
        //public virtual Teacher Teacher { get; set; }
    }
    public partial class Subject
    {
        [NotMapped]
        public List<Subject> SubjectList { get; set; }
    }
}

Classroom/Controllers/SubjectController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Classroom.Models;
using Classroom.Models.DB_Models;
using Classroom.Repository;
using System;
using System.Collections.Specialized;
using System.Data.Entity;
using System.Net;

namespace Classroom.Controllers
{
    // [Authorize(Roles = "User")]
    public class SubjectController : Controller
    {
        private ClassroomContext db = new ClassroomContext();
        List<Subject> subjectList = new List<Subject>();

        #region Constructors and Index
        public SubjectController()
        {
        }

        public SubjectController(List<Subject> subjects)
        {
            subjectList = subjects;
        }

        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.Error = true;
            try
            {
                var teacherId = new GetTeachers().GetTeacherIdByUsername(User.Identity.Name);
                var subjects = new GetSubjects().GetSubjectsByTeacherId(teacherId);
                var tasks = new GetTeacherTasks().GetAllTeacherTasks(teacherId);
                ViewBag.mySubjects = subjects;
                ViewBag.myTasks = tasks;
                ViewBag.Error = false;
            }
            catch(Exception ex)
            {
                ViewBag.ErrorMessage = "Log in to see your subjects.";

            }
            //return RedirectToAction("ChartMain"); --Uncomment to see average chart
            return View();
        }

        #endregion

        //#region ChartMain
        //public ActionResult ChartMain()
        //{
        //    ViewBag.DataFlag = false;
        //    if (User.Identity.Name.IsNullOrWhiteSpace())
        //    {
        //        ViewBag.DataFlag = true;
        //    }
        //    Subject subjects = new Subject();
        //    //Needs optimisation
        //    //Check if the student has 

        //    bool studMarks = db.Subjects.Any(s => s.Mark > 0 && db.Teacher.Select(x => x.UserName.Equals(User.Identity.Name) && x.Id.Equals(s.Student.Id)).Distinct().Count() > 1);
        //    ViewBag.hasMarks = studMarks;
        //    return View();
        //}

        //public ActionResult Chart()
        //{
        //    var subjects = db.Subjects.ToList();
        //    var students = db.Students.Where(s => s.TeacherId.Equals(db.Teacher.Select(t=>t.UserName.Equals(User.Identity.Name)))).ToList();
        //    ViewBag.errorMessage = "No student subject data to display. ";
        //    ViewBag.dataFlag = false;

        //    List<double> averages = new List<double>();
        //    List<string> names = new List<string>();
        //    int count = 0;
        //    bool flag = false;
        //    foreach (var x in subjects)
        //    {
        //        try
        //        {
        //            var studId = students[count].Id;
        //            if (x.Student.Id.Equals(studId))
        //            {
        //                var classSubj = db.Subjects.Where(s => s.Class.Id.Equals(studId)).ToList();
        //                double mark = 0, sum = 0;
        //                for (int i = 0; i < classSubj.Count; i++)
        //                {
        //                    mark = classSubj[i].Mark;
        //                    sum += mark;
        //                }
        //                averages.Add(sum / 7);
        //                var stud = db.Students.Find(x.Student.Id);
        //                names.Add(stud.FirstName + " " + stud.LastName);
        //            }
        //            count++;
        //        }
        //        catch (Exception ex)
        //        {
        //            //log issue or get better handling for no student ID error
        //            flag = true;
        //            break;
        //        }
        //    }

        //    ViewBag.Averages = averages;
        //    ViewBag.Names = names;

        //    if (names.Count < 1 || flag)
        //    {
        //        ViewBag.dataFlag = true;//There is no data to display
        //        return View();
        //    }

        //    var chart = new Chart(width: 600, height: 400, theme: ChartTheme.Vanilla)
        //        .AddTitle("Student Averages")
        //        .AddSeries(name: "Student marks", xValue: names, yValues: averages)
        //        .Write();

        //    return View();
        //}
        [HttpGet]
        public ActionResult AssignSubjects()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AssignSubjects([Bind(Include = "Id,Name")] Subject subject)
        {
            string subjectName = Request.Form["sDropdown"];
            var mySubject = new GetSubjects().GetSubjectByName(subjectName);
            var teacher = new GetTeachers().GetTeacherByUsername(User.Identity.Name);

            TeacherSubjects ts = new TeacherSubjects();
            ts.SubjectId = mySubject.Id;
            ts.TeacherId = teacher.Id;
            if(new GetTeacherSubjects().GetTeacherSubjectByTeacherIdAndSubjectId(ts.TeacherId, ts.SubjectId)== null)
            {
                db.TeacherSubjects.Add(ts);
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }
        //#endregion
        [HttpGet]
        [System.Web.Http.Route("Subject/SubjectView/{subject}")]
        public ActionResult SubjectView(string subject)
        {
            ViewBag.Subject = subject;
            var tasks = db.Tasks.ToList();
            return View(tasks);
        }
        public ActionResult AddTask(int id)
        {
                ViewBag.SubjectName = new GetSubjects().GetSubjectById(id).Name;
 
            return View();
        }
        [HttpPost]
        public ActionResult AddTask([Bind(Include = "Id,DateGiven,SubmissionDate,TaskName,Description,TeacherId,SubjectId")] Tasks Task)
        {
            NameValueCollection nvc = Request.Form;
            var TeacherId = new GetTeachers().GetTeacherIdByUsername(User.Identity.Name);// Remove?
            var mySubject = new GetSubjects().GetSubjectByName(Request.Form.Get("sname"));
            var teacher = new GetTeachers().GetTeacherByUsername(User.Identity.Name);
            //Use object injected!
            Tasks ts = new Tasks();
            ts.SubjectId = mySubject.Id;
            ts.TeacherId = teacher.Id;
            var d = Request.Form.Get("datepicker1");
            var date = DateTime.ParseExact(Request.Form.Get("datepicker1"),"M/dd/yyyy", null);
            ts.DateGiven = Convert.ToDateTime(date);
            date = DateTime.ParseExact(Request.Form.Get("datepicker2"), "M/dd/yyyy", null);
            ts.SubmissionDate = Convert.ToDateTime(date);
            ts.TaskName = Request.Form.Get("TaskName");
            ts.Description = Request.Form.Get("Description");
            
            //if (ts.Id == 0)
            //{
            //    ts.Id = 1;
            //}
            db.Tasks.Add(ts);
            db.SaveChanges();
            var students = new GetStudents().GetStudentsByTeacherUsername(User.Identity.Name);
            foreach(var item in students)
            {
                StudentTasks st = new StudentTasks();
                st.StudentId = item.Id;
                st.TaskId = ts.Id;
                st.Id = (st.Id==0) ? 1 : st.Id;
                db.StudentTasks.Add(st);
                db.SaveChanges();
            }
            try
            {
                db.SaveChanges();
            }
            catch (Exception ex)
            {

            }

            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult StudentTasks(int? id)
        {
            //Insert TRY BLOCK to improve exception handling
            string[] sid = Request.Url.ToString().Split('/');
            int nid = Convert.ToInt32(sid[sid.Length - 1]);//Get task ID from url
            List<StudentTasks> sTasks = new GetStudentTasks().GetStudentTasksByTasksId(nid);
            List<Student> students = new List<Student>();
            GetStudents student = new GetStudents();
            var mark = Request;
            Tasks tasks = new Tasks();
            try
            {
                tasks = new GetTeacherTasks().GetTasksById(sTasks[0].TaskId);
            }
            catch(Exception ex)
            {
                //
            }

            foreach (var item in sTasks)
            {
                var x = student.GetStudentById(item.StudentId);
                students.Add(x);
            }
            ViewBag.sTask = sTasks;
            ViewBag.Students = students;
            ViewBag.Task = tasks;
            return View(sTasks);
        }
        [HttpPost]
        public ActionResult StudentTasks(string content)
        {
            var marks = Request.Form.ToString();
            var indiMarks = marks.Split('.');

            foreach(var item in indiMarks)
            {
                var temp = item.Split('a');
                if (temp[0] == "")
                {
                    break;
                }
                StudentTasks sTask = db.StudentTasks.Find(Convert.ToInt32(temp[0]));
                sTask.Mark = Convert.ToDouble(temp[1]);
                
                db.StudentTasks.SqlQuery("Update StudentTasks Set Mark=" + temp[1] + "Where Id=" + temp[1]);
                db.SaveChanges();
            }

            return View();
        }
        // GET: /Student/Edit/5
        public ActionResult EditMark(int? id)
        {
            int nid = id ?? 0;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentTasks sTask = db.StudentTasks.Find(id);
            if (sTask == null)
            {
                return HttpNotFound();
            }
            var student = new GetStudents().GetStudentByStudentTaskId(nid);
            ViewBag.student = student;
            return View(sTask);
        }

Classroom/Views/Subject/AddTask.cshtml
@model Classroom.Models.DB_Models.Tasks

@{
    ViewBag.Title = "AddTask";
    ViewBag.SubjectNameIn = ViewBag.SubjectName==null ? "" : ViewBag.SubjectName;
}

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" href="/resources/demos/style.css">
<script>
  $(function() {
      $("#datepicker1").datepicker({
          onSelect: function (dateText1, inst) {
              $("input[name='dp1']").val(dateText1);
          }
      });
      $("#datepicker2").datepicker({
          onSelect: function (dateText2, inst) {
              $("input[name='dp2']").val(dateText2);
          }
      });;
  });
</script>

<h2>AddTask</h2>

<h4 id="SubjectTitle" name="SubjectTitle" key="11">@ViewBag.SubjectName</h4>
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <input type="hidden" name="sname" value="@ViewBag.SubjectName" />
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true)
        @*<div class="form-group">
            @Html.LabelFor(model => model.SubjectsId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SubjectsId)
                @Html.ValidationMessageFor(model => model.SubjectsId)
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.DateGiven, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.DateGiven)*@
                <input type="text" id="datepicker1" name="datepicker1">
                @Html.ValidationMessageFor(model => model.DateGiven)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubmissionDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.SubmissionDate)*@
                <input type="text" id="datepicker2" name="datepicker2">
                @Html.ValidationMessageFor(model => model.SubmissionDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TaskName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TaskName)
                @Html.ValidationMessageFor(model => model.TaskName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.TeacherId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TeacherId)
                @Html.ValidationMessageFor(model => model.TeacherId)
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Classroom/Views/Subject/AssignSubjects.cshtml
@model Classroom.Models.DB_Models.Subject

@{
    ViewBag.Title = "AssignSubjects";
}

<h2>Assign Subjects</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Assign subject to current user</h4>
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)*@
                @* Subject dropdown menu *@
                <select id="SubjectDropdown" name="sDropdown">
                    <option value = "English">English</option>
                    <option value = "Afrikaans">Afrikaans</option>
                    <option value = "Math">Math</option>
                    <option value = "Geography">Geography</option>
                    <option value = "History">History</option>
                    <option value = "Life Orientation">Life Orientation</option>
                    <option value = "Natural Science">Natural Science</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Assign to me" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index") 
</div>

Classroom/Views/Subject/Chart.cshtml
@*@{
    ViewBag.Title = "Chart";
}*@

@if (ViewBag.dataFlag == true)
{
    <h2>
        No student subject data, @Html.ActionLink("Create some...", "Class", "Student")
    </h2>
}

Classroom/Views/Subject/ChartMain.cshtml
@if (ViewBag.dataFlag || !ViewBag.hasMarks)
{
    <h2>
        No student subject data, @Html.ActionLink("Create some...", "Class", "Student")
    </h2>
}
else
{

    <h2>Class Overview</h2>

    <br />
    <style>
        img {
            border: 2px solid #9da1a8;
        }
    </style>

    var url = @Url.Action("Chart", "Subject");

    <div align="center">
        <img src=@url />
    </div>
}

Classroom/Views/Subject/DeleteStudentTask.cshtml
@model Classroom.Models.DB_Models.Tasks

@{
    ViewBag.Title = "DeleteStudentTask";
}

<h2>DeleteStudentTask</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tasks</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SubjectId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubjectId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateGiven)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateGiven)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubmissionDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubmissionDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TaskName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaskName) 
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TeacherId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TeacherId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Classroom/Views/Subject/EditMark.cshtml
@model Classroom.Models.DB_Models.StudentTasks

@{
    ViewBag.Title = "EditMark";
}

<h2>EditMark</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@ViewBag.student.FirstName @ViewBag.student.LastName</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

@Html.HiddenFor(model => model.StudentId)

@Html.HiddenFor(model => model.TaskId)
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mark, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mark)
                @Html.ValidationMessageFor(model => model.Mark)
            </div>
        </div>
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Classroom/Views/Subject/Index.cshtml
@model List<Classroom.Models.DB_Models.Subject>
@{
    ViewBag.Title = "Index";
}
@if (!ViewBag.Error)
{
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css" type="text/css">
  <script type="text/javascript" src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script type="text/javascript" src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  @*<link rel="stylesheet" href="/resources/demos/style.css">*@
  @*<link href="~/Content/jquery-ui.css" rel="stylesheet" />*@

  <style>
  /* IE has layout issues when sorting (see #5413) */
  .group { zoom: 1 }
  </style>
  <script>
      $(function() {
        $( "#accordion" )
          .accordion({
              header: "> div > h3",
              collapsible: true
          })
          .sortable({
            axis: "y",
            handle: "h3",
            stop: function( event, ui ) {
              // IE doesn't register the blur when sorting
              // so trigger focusout handlers to remove .ui-state-focus
              ui.item.children( "h3" ).triggerHandler( "focusout" );
 
              // Refresh accordion to handle new order
              $( this ).accordion( "refresh" );
            }
          });
      });
  </script>

<h2>My Subjects</h2>
<br/>
<h4><!--Needs Optimization-->
    @if (ViewBag.Error)
    {
        @ViewBag.ErrorMessage
    }
    else
    {
        @Html.ActionLink("Assign subjects to user", "AssignSubjects")
        <br />
    }
</h4>
<h4>
    <u>My Subjects:</u>
</h4>

    <div id="accordion">
    @for (int i = 0; i < ViewBag.mySubjects.Count; i++)
    {
        var name = ViewBag.mySubjects[i].Name;
        var sId = ViewBag.mySubjects[i].Id;
        var tasks = ViewBag.myTasks;
        <div class="group">
            <h3>@Html.ActionLink((string)name, "SubjectView", new { id = sId })</h3>
            <div>
               @* <p>Tasks to be included here...</p>*@
                @Html.ActionLink("Add new task", "AddTask", new { id = sId })

                <table>
                    <tr>
                        <th>
                            @Html.DisplayName("Date Given")
                        </th>
                        <th>
                            @Html.DisplayName("Submission Date")
                        </th>
                        <th>
                            @Html.DisplayName("Task Name")
                        </th>
                        <th>
                            @Html.DisplayName("Description")
                        </th>
                    </tr>
                    @for (int j = 0; j < tasks.Count; j++)
                    {
                        if (tasks[j].SubjectId == sId)
                        {
                            <tr>
                                <th>
                                    <h5> @tasks[j].DateGiven.Date</h5>
                                </th>
                                <th>
                                    <h5> @tasks[j].SubmissionDate.Date</h5>
                                </th>
                                <th>
                                    <h5> @tasks[j].TaskName</h5>
                                </th>
                                <th>
                                    <h5> @tasks[j].Description</h5>
                                </th>
                                <th>
                                    @Html.ActionLink("Show student marks for this task", "StudentTasks", new { id = tasks[j].Id }) |
                                </th>
                                <th>
                                    @Html.ActionLink("Delete Task", "DeleteStudentTask", new { id = tasks[j].Id })
                                </th>
                            </tr>
                        }
                    }
                  </table>
            </div>
        </div>
    }
    </div>

}
else
{
    <h3> @ViewBag.errorMessage</h3>
}



    @*using (Html.BeginForm())
    {
         <h2>Class Overview</h2>
<br/>

    <style>
        img {
            border: 2px solid #9da1a8;
        }
    </style>

    <div align="center">           
        Graph can also be drawn from DB data (http://www.w3schools.com/aspnet/webpages_chart.asp)
        <img src='@Url.Action("ChartMain", "Subject")'/>
    </div>*@

Classroom/Views/Subject/StudentTasks.cshtml
@model List<Classroom.Models.DB_Models.StudentTasks>

@{
    ViewBag.Title = "StudentTasks";
}

<h2>@ViewBag.TaskName</h2>
<h4>Possible other heading here</h4>
@{
    var stasks = ViewBag.sTask;
    var students = ViewBag.Students;
    var tId = ViewBag.Task.Id;
    string[] mrks = new string[stasks.Count];
    var mIds = "mark";
    int i = 0;
    string[] ids = new string[stasks.Count];
}

<table draggable="true" title="StudentMarks">
    <tr>
        <th>

        </th>
        <th>
            @Html.DisplayName("Student Name")
        </th>
        <th>
            @Html.DisplayName("Mark")
        </th>
        <th>

        </th>
    </tr>
    @try
    {

        foreach (var item in Model)
        {
            //ids[i] = stasks[i].Id.ToString();
            if (item.TaskId.Equals(tId))
            {
                mIds = mIds.Substring(0, 4) + (i + 1);
            <tr>
                <th id="@i" name="@i">
                    @item.Id
                    
                </th="@item.Id">
                <th>
                    @students[i].FirstName
                    @students[i].LastName
                </th>
                <th id="@mIds" name="@mIds" contenteditable="true">
                    @item.Mark
                </th>
                <th>
                    @Html.ActionLink("Edit", "EditMark", new { id = item.Id })
                </th>
            </tr>
            }
            i++;
        }
    }
    catch (Exception ex)
    {

        //Log error and inform users
    }
</table>
<br />
    <a href='@Url.Action("StudentTasks", "Subject")' onclick='save(this.href);'>
        <input type="button" value='Submit' />
    </a>
  
<script>
    function save(target)
    {
        //alert("Here");
        var j = 1;
        var id = "mark" + j;
        var content = "";
        @{i = 0; }
        //var arr = new array(@i);
        while (document.getElementById(id))
        {
            try{
                //alert("in");
                 content += document.getElementById(j-1).innerText+"a"+document.getElementById(id).innerText+".";
                //arr[j-1] = content;
                j++;
                @{i++; }
                    id = "mark" + (j);
            }
            catch (err) { alert("Exception"); }

        }
        $.post(target, content);
        //alert("END");
    }
</script>

Classroom/Views/Subject/SubjectView.cshtml
@model List<Classroom.Models.TaskManager>
@{
    ViewBag.Title = "SubjectView";
}

<h2>@ViewBag.Subject</h2>

<h3>Tasks and Assignments</h3>
<script>
    $(function() {
        $("#accordion").accordion({
            collapsible: true
        });
    });
</script>
<div id="accordion">
    @foreach (var item in Model)
    {
        <h3>@Html.DisplayFor(modelItem => item.TaskList)</h3>
        <div>
            <p>@Html.DisplayFor(modelItem => item.Description)</p>
            <table>
                <tr>
                    <th>
                        @Html.DisplayName("Date Given")
                    </th>
                    <th>
                        @Html.DisplayName("Submission Data")
                    </th>
                    <th>
                        @Html.DisplayName("Mark")
                    </th>
                </tr>
                <tr>
                    <th>
                        @Html.DisplayFor(modelItem => item.DateGiven)
                    </th>
                    <th>
                        @Html.DisplayFor(modelItem => item.SubmissionDate)
                    </th>
                    <th>
                        @Html.DisplayFor(modelItem => item.MarkGiven)
                    </th>
                </tr>
            </table>
        </div>
    }
    <h3></h3>
</div>